name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          known_hosts: ssh-keyscan -H ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_GITHUB_ACTION_PRIVATE }}
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Checkout submodules
        uses: srt32/git-actions@v0.0.3
        with:
          args: git submodule update --init --recursive
      - name: Build Executable
        run: make
