name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: git submodule
        run: git submodule update
      - name: build
        run: make
