name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Executable
    steps:
      - name: Checkout repo & libft
        uses: actions/checkout@v2
        with:
          # token: ${{ secrets.CI_TOKEN }}
          submodules: true
      - name: Norminette
        uses: alexandregv/norminette-action@v3
        with:
          flags: 'includes srcs'
        continue-on-error: true
      - name: Make
        run: make
      - name: Clean
        run: make clean
      - name: Clean Executable
        run: make fclean
  build_macos:
    runs-on: macos-latest
    name: Build Executable on macOS
    steps:
      - name: Checkout repo & libft
        uses: actions/checkout@v2
        with:
          # token: ${{ secrets.CI_TOKEN }}
          submodules: true
      - name: Make
        run: make
      - name: Clean
        run: make clean
      - name: Clean Executable
        run: make fclean
