name: Build Linux

on: [push, pull_request]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    name: Build Executable on Linux
    steps:
      - name: Checkout repo & libft
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Make
        run: make
      - name: Clean
        run: |
            make clean
            make fclean

