name: Compilation

on: [push, pull_request]

jobs:
  norminette_job:
    runs-on: ubuntu-latest
    name: norminette
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Checkout submodules
        uses: srt32/git-actions@v0.0.3
        with:
          args: git submodule update --init
      - uses: alexandregv/norminette-action@v3
        with:
          flags: 'includes srcs libft'
  build_launch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Checkout submodules
        uses: srt32/git-actions@v0.0.3
        with:
          args: git submodule update --init
      - name: Build Executable
        run: sudo make
      - name: Launch
        run: ./minishell
      - name: 42valgrind Leak checker
        uses: solareenlo/42valgrind-action@v1.0.3
        with:
          flags: 'sh scipts/leaks.sh'
