name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: 42 Norminette
      uses: alexandregv/norminette-action@v3
    - uses: actions/checkout@v2
    - name: make
      run: make
