name: Launch Main

on: [push, pull_request]

jobs:
  launch:
    runs-on: ubuntu-latest
    name: Launch Main Executable
    steps:
      - name: Checkout repo & libft
        uses: actions/checkout@v2
        with:
          # token: ${{ secrets.CI_TOKEN }}
          submodules: true
      - name: Make
        run: make
      - name: Launch
        run: ./minishell
  launch_macos:
    runs-on: macos-latest
    name: Launch Main Executable on macOS
    steps:
      - name: Checkout repo & libft
        uses: actions/checkout@v2
        with:
          # token: ${{ secrets.CI_TOKEN }}
          submodules: true
      - name: Make
        run: make
      - name: Launch
        run: ./minishell
