name: Launch_Main

on: [push, pull_request]

jobs:
  launch:
    runs-on: ubuntu-latest
    name: Launch Main Executable
    steps:
      - name: Checkout repo & Libft
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Print Informations for Segfault
        run: |
          make re CFLAGS='-Wall -Wextra -g3 -fsanitize=address' > /dev/null
          ./minishell
      - name: Make
        run: make re
      - name: Start Minishell
        run: ./minishell
      - name: Valgrind - Leak Checker
        uses: solareenlo/42valgrind-action@v1.0.3
        with:
          flags: 'valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes ./minishell'
  launch_macos:
    runs-on: macos-latest
    name: Launch Main Executable on macOS
    steps:
      - name: Checkout repo & libft
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Print Informations for Segfault
        run: |
          make re CFLAGS='-Wall -Wextra -g3 -fsanitize=address' > /dev/null
          ./minishell
      - name: Make
        run: make re
      - name: Launch
        run: ./minishell
      - name: Copy libLeaksAtExit.dylib
        run: |
          cd /usr/local/lib
          sudo ln -s /Applications/Xcode.app//Contents/Developer/usr/lib/libLeaksAtExit.dylib
      - name: Leaks - Leak Checker
        run: leaks -atExit -- ./minishell
        shell: bash
