name: Libft_Check

on: [push, pull_request]

jobs:
  libft:
    runs-on: ubuntu-latest
    name: Norm/Build Libft
    steps:
      - name: Checkout repo & Libft
        uses: actions/checkout@v2
        with:
          submodules: true
        continue-on-error: true
      - name: Norminette on Libft
        uses: alexandregv/norminette-action@v3
        with:
          flags: 'libft'
        continue-on-error: true
      - name: Make Libft
        run: cd libft && make
        continue-on-error: true
      - name: Clean Libft Projet
        run: cd libft && make clean
        continue-on-error: true
      - name: Clean Libft.a
        run: cd libft && make fclean
        continue-on-error: true
