name: Norminette

on: [push, pull_request]

jobs:
  norminette_job:
    runs-on: ubuntu-latest
    name: Norminette Sources
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: alexandregv/norminette-action@v3
        with:
          flags: 'includes scripts/leaks.sh'
