name: Launch Tester Linux

on: [push, pull_request]

jobs:
  launch:
    runs-on: ubuntu-latest
    name: Launch Main Executable
    steps:
      - name: Checkout repo, Libft & Tester
        uses: actions/checkout@v2
        with:
          submodules: true
        continue-on-error: true
      - name: Launch Tester
        run: ./scripts/tester.sh
      - name: Commands to fix
        run: cat minishell_tester/tofix/tofix_tests.txt
