name: Launch Tester

on: [push, pull_request]

jobs:
  launch_tester_linux:
    runs-on: ubuntu-latest
    name: Tester Linux
    steps:
      - name: Checkout repo, Libft & Tester
        uses: actions/checkout@v2
        with:
          submodules: true
        continue-on-error: true
      - name: Install Progs for Tester
        run: |
          sudo apt update
          sudo apt-get install -y bash diffutils python3 pip gcc clang build-essential valgrind apt-utils libreadline-dev
          python3 -m pip install --upgrade pip setuptools
          python3 -m pip install norminette
      - name: Check Compatibility Tester
        run: cd minishell_tester && bash test.sh compatibility
      - name: Launch Tester
        run: cd minishell_tester && bash test.sh all
        shell: bash
      - name: Commands to fix
        run: cat minishell_tester/tofix/tofix_tests.txt
  launch_tester_macos:
    runs-on: macos-latest
    name: Tester Linux
    steps:
      - name: Checkout repo, Libft & Tester
        uses: actions/checkout@v2
        with:
          submodules: true
        continue-on-error: true
      - name: Install Progs for Tester
        run: |
          sudo apt update
          sudo apt-get install -y bash diffutils python3 pip gcc clang build-essential valgrind apt-utils libreadline-dev
          python3 -m pip install --upgrade pip setuptools
          python3 -m pip install norminette
      - name: Check Compatibility Tester
        run: cd minishell_tester && bash test.sh compatibility
      - name: Launch Tester
        run: cd minishell_tester && bash test.sh all
        shell: bash
      - name: Commands to fix
        run: cat minishell_tester/tofix/tofix_tests.txt
